import type { ClientPortalSettings, CostoItem, ModulosContratados } from '@/types/fiesta';
import type { ItemPresupuestado } from '@/types/presupuesto';
import { defaultClientPortalSettings } from '@/lib/fiesta-defaults';

export function normalizeBudgetItemsForSync(items: ItemPresupuestado[] | null | undefined): ItemPresupuestado[] {
  if (!Array.isArray(items)) return [];
  return items.filter((item): item is ItemPresupuestado => !!item && typeof item === 'object');
}

function normalizeServiceText(value: unknown): string {
  return String(value ?? '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

export function deriveBudgetModulesForSync(
  budgetItems: ItemPresupuestado[] | null | undefined
): Partial<ModulosContratados> {
  const searchableItems = normalizeBudgetItemsForSync(budgetItems).map(item =>
    normalizeServiceText([
      item.nombreServicio,
      item.nombre,
      item.descripcionServicio,
      item.categoriaServicio,
      item.subcategoria,
    ].filter(Boolean).join(' '))
  );
  const hasAny = (...terms: string[]) => searchableItems.some(text =>
    terms.some(term => text.includes(normalizeServiceText(term)))
  );

  return {
    redSocial: hasAny('red social', 'feed social', 'social privado'),
    muroSocial: hasAny('muro social', 'muro interactivo', 'mural social', 'pantalla social'),
    barraTecnologica: hasAny('barra tecnologica', 'barra interactiva', 'carta digital de tragos', 'pedido digital de tragos'),
    zonaDigital: hasAny('zona digital', 'juegos digitales', 'retos digitales', 'experiencia adolescente'),
    pantallasTotem: hasAny('pantalla totem', 'pantallas totem', 'totem interactivo'),
    entretenimiento: hasAny('fotocabina', 'plataforma 360', 'cabina 360', 'espejo magico', 'bogue', 'touchpix', 'face swap'),
    paginaWeb: hasAny('invitacion digital', 'invitacion web', 'pagina web del evento', 'web del evento'),
    buzon: hasAny('buzon de recuerdos', 'buzon de mensajes', 'buzon audiovisual', 'audio guestbook'),
  };
}

export function mergeClientPortalSettingsForSync(current?: ClientPortalSettings): ClientPortalSettings {
  const existing: Partial<ClientPortalSettings> = current || {};
  return {
    ...defaultClientPortalSettings,
    ...existing,
    enabled: true, // force enable when syncing from budget
    checklist: { ...existing.checklist, visible: true, editable: true },
    itinerario: { ...existing.itinerario, visible: true },
    musica: { ...existing.musica, visible: true, editable: true },
    videoVida: { ...existing.videoVida, visible: true, editable: true },
    listaRegalos: { ...existing.listaRegalos, visible: true },
    documentos: { ...existing.documentos, visible: true },
    notasCliente: { ...existing.notasCliente, visible: true, editable: true },
    invitados: { ...existing.invitados, visible: true },
    fotografiaYFilmacion: { ...existing.fotografiaYFilmacion, visible: true },
    moodboard: { ...existing.moodboard, visible: true, editable: true },
    buzon: { ...existing.buzon, visible: true, editable: true },
    contrato: { ...existing.contrato, visible: true },
    pagos: { ...existing.pagos, visible: true },
    calculadoraBebidas: { items: defaultClientPortalSettings.calculadoraBebidas?.items ?? [], ...existing.calculadoraBebidas, visible: true },
    menu: { ...existing.menu, visible: true },
    cartaTragos: { ...existing.cartaTragos, visible: true },
    dressCode: { ...existing.dressCode, visible: true },
    faq: { ...existing.faq, visible: true },
    informarPago: { ...existing.informarPago, visible: true, editable: true },
  };
}

export function replaceAutoGeneratedCostItems(
  currentItems: CostoItem[] = [],
  generatedItems: CostoItem[] = [],
): CostoItem[] {
  return [
    ...currentItems.filter(item => !item.id.startsWith('auto_')),
    ...generatedItems,
  ];
}

export function applyLaundryCosts(
  baseItems: CostoItem[],
  guests: number,
  budgetItems: ItemPresupuestado[] | null | undefined
): CostoItem[] {
  const items = baseItems.map(item => ({ ...item }));
  const safeItems = Array.isArray(budgetItems) ? budgetItems : [];
  const hasMantel = safeItems.some(i => (i?.nombreServicio || '').toLowerCase().includes('mantel'));
  const hasCompleta = safeItems.some(i => (i?.nombreServicio || '').toLowerCase().includes('completa'));

  const updateOrCreateCost = (name: string, amount: number) => {
    const index = items.findIndex(i => i.nombre === name);
    if (amount > 0) {
      if (index > -1) {
        items[index].montoEstimado = Math.round(amount);
      } else {
        const stableIdPart = name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
        items.push({
          id: `laundry_${stableIdPart}`,
          nombre: name,
          category: 'Servicio Proveedor',
          montoEstimado: Math.round(amount),
          notas: 'Auto-generado: Lavadero del Sol'
        });
      }
    } else if (index > -1) {
      items.splice(index, 1);
    }
  };

  if (hasMantel) {
    const normalizedGuests = Math.max(0, Math.round(guests || 0));
    const units = Math.ceil(normalizedGuests / 8);
    updateOrCreateCost('Lavado Mantel ($50)', units * 50);
    updateOrCreateCost('Lavado Cubre ($18)', units * 18);
    if (hasCompleta) {
      updateOrCreateCost('Lavado Cubre Silla ($18)', normalizedGuests * 18);
    }
  } else {
    updateOrCreateCost('Lavado Mantel ($50)', 0);
    updateOrCreateCost('Lavado Cubre ($18)', 0);
    updateOrCreateCost('Lavado Cubre Silla ($18)', 0);
  }

  return items;
}
