'use server';

import type { FiestaEnPlanificacion, GestionCostosData, CostoItem, PagoProveedor } from '@/types/fiesta';
import type { ItemPresupuestado } from '@/types/presupuesto';
import { getFiestaById, saveFiesta, updateFiestaPartial } from './fiesta.actions';
import { getPresupuestoById } from '../presupuestos';
import { getGuestCountForItem } from '@/lib/calculations';
import { getServiciosEmpresa } from '../servicios-empresa';
import { getMenus } from '../menus-catering';
import { getRoles } from '../roles';
import { getInsumos } from '../insumos';
import { applyLaundryCosts, replaceAutoGeneratedCostItems } from '@/lib/fiesta-sync-utils';

export async function updateGestionCostos(fiestaId: string, costos: GestionCostosData): Promise<{ success: boolean; updatedData?: GestionCostosData; error?: string }> {
  try {
    const result = await updateFiestaPartial(fiestaId, { gestionCostos: costos });
    if (!result.success) throw new Error(result.error);
    return { success: true, updatedData: costos };
  } catch (e: any) {
    return { success: false, error: e.message };
  }
}

/**
 * MOTOR FINANCIERO INTEGRAL: Sincroniza todos los gastos operativos del evento.
 */
export async function syncAllEventCosts(fiestaId: string): Promise<{ success: boolean; error?: string }> {
    if (!fiestaId) return { success: false, error: "ID no válido" };

    try {
        const fiesta = await getFiestaById(fiestaId);
        if (!fiesta) throw new Error("Evento no encontrado");

        const [presupuesto, catalogServices, catalogInsumos, allMenus, roles] = await Promise.all([
            fiesta.presupuestoId ? getPresupuestoById(fiesta.presupuestoId) : Promise.resolve(null),
            getServiciosEmpresa(),
            getInsumos(),
            getMenus(),
            getRoles()
        ]);

        if (!presupuesto) return { success: false, error: "No hay presupuesto vinculado" };

        const adultos = presupuesto.invitadosAdultos || 0;
        const adolescentes = presupuesto.invitadosAdolescentes || 0;
        const ninos = presupuesto.invitadosNinos || 0;
        const totalInv = adultos + adolescentes + ninos;

        let totalCateringCost = 0;
        let totalPersonalCost = 0;
        let totalBebidasCost = 0;
        let totalReposteriaCost = 0;

        const autoCostItems: CostoItem[] = [];

        // 1. SINCRONIZACIÓN DE PERSONAL (SUELDOS + APORTES)
        // Incluye vacantes proyectadas si no hay empleados asignados
        if (fiesta.personalAsignado && fiesta.personalAsignado.length > 0) {
            fiesta.personalAsignado.forEach(pa => {
                const rol = roles.find(r => r.id === pa.rolId);
                const sueldo = pa.eventSalary || rol?.sueldoPorEvento || 0;
                const aportes = (sueldo * (rol?.porcentajeAportesPatronales || 0)) / 100;
                totalPersonalCost += sueldo + aportes;
            });
        }

        // 2. SINCRONIZACIÓN GASTRONÓMICA (RECETAS)
        if (fiesta.menuAsignadoId) {
            const menu = allMenus.find(m => m.id === fiesta.menuAsignadoId);
            if (menu) {
                menu.items.forEach(plato => {
                    const targetGuests = getGuestCountForItem({ nombreServicio: plato.name, categoriaServicio: plato.type }, adultos, adolescentes, ninos);
                    totalCateringCost += (plato.totalDishCost || 0) * targetGuests;
                });
            }
        }

        // 3. SINCRONIZACIÓN DE BEBIDAS Y REPOSTERÍA
        if (fiesta.bebidas?.categorias) {
            let bebidasBaseCost = 0;
            fiesta.bebidas.categorias.filter(c => c.activada).forEach(cat => {
                cat.items.forEach(item => {
                    const cost = item.costoUnitario || 0;
                    const qtyPerPerson = item.cantidadNecesaria || 0;
                    bebidasBaseCost += cost * qtyPerPerson * totalInv;
                });
            });
            // Merma de bebidas (5% extra)
            totalBebidasCost = bebidasBaseCost * 1.05;
            if (bebidasBaseCost > 0) {
                autoCostItems.push({
                    id: `auto_merma_bebidas`,
                    nombre: `Merma de Bebidas (5%)`,
                    category: 'Insumos',
                    montoEstimado: Math.round(totalBebidasCost - bebidasBaseCost),
                    notas: 'Factor de desperdicio operativo.'
                });
            }
        }
        if (fiesta.reposteria?.categorias) {
            fiesta.reposteria.categorias.filter(c => c.activada).forEach(cat => {
                cat.items.forEach(item => {
                    totalReposteriaCost += (item.costoEstimado || 0) * (item.cantidad || 1);
                });
            });
        }

        // 4. AUDITORÍA DEL PRESUPUESTO Y 5. AMORTIZACIÓN (PROVEEDORES EXTERNOS Y ACTIVOS)
        let totalAmortizacion = 0;
        presupuesto.itemsPresupuestados.forEach(item => {
            if (item.esRegalo) return;
            const catalogItem = catalogServices.find(c => c.id === item.idServicioCatalogo);
            
            // Proveedores y Gastos Fijos
            if (catalogItem?.tipoCosto === 'Proveedor' || catalogItem?.tipoCosto === 'Gasto Fijo' || catalogItem?.categoria?.includes('Salón')) {
                const costoUnitario = catalogItem.valorUnitarioEstimado || 0;
                const targetGuests = getGuestCountForItem({ nombreServicio: item.nombreServicio, categoriaServicio: item.categoriaServicio, subcategoria: item.subcategoria }, adultos, adolescentes, ninos);
                
                let qty = item.cantidad || 1;
                if (catalogItem.calculationMethod === 'porPersona') qty = targetGuests;
                else if (catalogItem.calculationMethod === 'ratio' && catalogItem.invitadosPorUnidad) qty = Math.ceil(targetGuests / catalogItem.invitadosPorUnidad);

                const totalLineCost = costoUnitario * qty;
                if (totalLineCost > 0) {
                    autoCostItems.push({
                        id: `auto_prov_${catalogItem.id}`,
                        nombre: `${item.nombreServicio} (Costo Proveedor)`,
                        category: 'Servicio Proveedor',
                        montoEstimado: Math.round(totalLineCost),
                        notas: 'Sincronizado de Presupuesto.'
                    });
                }
            }
            
            // Amortización (Tecnología y Discoteca) - Asumimos 2% del valor de activo estimado
            if (catalogItem?.categoria?.includes('Discoteca') || catalogItem?.categoria?.includes('Iluminación') || catalogItem?.categoria?.includes('Infraestructura')) {
                // El valor estimado del equipo es ~10x el alquiler. Aplicamos 2% de desgaste sobre ese valor.
                const valorEstimadoEquipo = (catalogItem.valorUnitarioEstimado || 0) * 10;
                const desgaste = valorEstimadoEquipo * 0.02;
                if (desgaste > 0) totalAmortizacion += desgaste;
            }
        });

        if (totalAmortizacion > 0) {
            autoCostItems.push({
                id: `auto_amort_tech`,
                nombre: `Amortización de Equipos y Tecnología (2%)`,
                category: 'Gasto Fijo',
                montoEstimado: Math.round(totalAmortizacion),
                notas: 'Cargo contable por desgaste de activos fijos.'
            });
        }

        const currentCosts = fiesta.gestionCostos || { costosItems: [], ingresosTotalesEstimados: 0 };
        const syncedCostItems = replaceAutoGeneratedCostItems(currentCosts.costosItems, autoCostItems);

        const updatedGestion: GestionCostosData = {
            ...currentCosts,
            ingresosTotalesEstimados: Math.round(presupuesto.totalConDescuento ?? presupuesto.costoTotalEstimado),
            costosItems: syncedCostItems,
            others: {
                totalCateringCost: Math.round(totalCateringCost),
                totalPersonalCost: Math.round(totalPersonalCost),
                totalBebidasCost: Math.round(totalBebidasCost),
                totalReposteriaCost: Math.round(totalReposteriaCost),
                totalProveedorCost: Math.round(
                    autoCostItems
                        .filter(item => item.id.startsWith('auto_prov_'))
                        .reduce((sum, item) => sum + item.montoEstimado, 0)
                )
            }
        };

        await updateGestionCostos(fiestaId, updatedGestion);
        return { success: true };

    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

export async function syncLaundryCosts(fiestaId: string, guests: number, budgetItems: ItemPresupuestado[] | null | undefined): Promise<void> {
    if (!fiestaId || !budgetItems) return;
    const fiesta = await getFiestaById(fiestaId);
    if (!fiesta) return;

    const costs = fiesta.gestionCostos || { costosItems: [], ingresosTotalesEstimados: 0 };
    const items = applyLaundryCosts(costs.costosItems || [], guests, budgetItems);
    await updateGestionCostos(fiestaId, { ...costs, costosItems: items });
}
